#!/usr/bin/env bash
# This script lists the content of the current directory in a specific format

for file in */
do
    if [[ "$file" != .* && "$file" == *-* ]]; then
        echo "${file#*-}"
    fi
done
